title: "Krishnaraj Yadav"
email: krishnay.75676@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Krishnaraj Yadav and I am very enthusisatic person to learn new things 
baseurl: "/" 
url: "https:krishna-y2000.github.io/" 
github_username:  krishna-y2000

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
incremental: true
